#!/bin/bash
../queuedata/read.sh
cp queuedata_rbfgrad.txt /home/samba_shared_dir
../iproute2-3.1.0/tc/tc qdisc del dev eth0 root
rmmod ../queuedata/seqfile_queuedata_rbfgrad.ko
rmmod ../modules/sch_rbfgrad.ko

